kind: ServiceAccount
apiVersion: v1
metadata:
  name: examplesrv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: examplesrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examplesrv
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: examplesrv
    spec:
      serviceAccountName: examplesrv
      containers:
        - name: examplesrv
          image: examplesrv:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: examplesrv-config
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: examplesrv
spec:
  selector:
    app: examplesrv
  clusterIP: None
  ports:
    - port: 8888
      targetPort: 8888
